version: 2
updates:
  # Python dependencies
  - package-ecosystem: "uv"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Compose dependencies
  - package-ecosystem: "docker-compose"
    directory: "/deploy"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
